apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: snp-kafka
  labels:
    app: kafka-app
spec:
  clusterIP: None 
  # type: LoadBalancer 
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: snp-kafka
  labels:
    app: kafka-app
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      securityContext: 
        fsGroup: 1000
      containers:
        - name: kafka-container
          image: bitnami/kafka:3.9
          ports:
            - containerPort: 9092
            # - containerPort: 9093
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: NAMESPACE
              value: snp-kafka
            # - name: CLUSTER_ID
            #   value: oh-sxaDRTcyAr6pFRbXyzA
            # - name: DEFAULT_REPLICATION_FACTOR
            #   value: '3'
            # - name: DEFAULT_MIN_INSYNC_REPLICAS
            #   value: '2'
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            # - name: KAFKA_DELETE_TOPIC_ENABLE
            #   value: "false"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
          volumeMounts:
            - name: kafka-storage
              # mountPath: /var/lib/kafka/data
              mountPath: /var/lib/kafka
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc  
