apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: snp-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.9
          env:
            - name: ZOO_PORT_NUMBER
              value: "2181"
            - name: ZOO_TICK_TIME
              value: "2000"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "true"
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: snp-kafka
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper